name: flagsmith_flutter_core
description: >-
  Core Package of Flutter Client SDK for https://www.flagsmith.com/, Flagsmith is 100% Open
  Source. Host yourself or let us take care of the hosting.

version: 2.4.0
homepage: https://github.com/Flagsmith/flagsmith-flutter-core
repository: https://github.com/Flagsmith/flagsmith-flutter-core
issue_tracker: https://github.com/Flagsmith/flagsmith-flutter-core/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  encrypt: ^5.0.1
  rxdart: ^0.27.5
  json_annotation: ^4.0.1
  collection: ^1.15.0
dev_dependencies:
  flutter_lints: ^1.0.0
  test:  ">=1.16.0 <=1.17.12"
  http_mock_adapter: ^0.3.2
  mockito: ^5.0.15
  json_serializable: ^4.1.3
  build_runner: ^2.1.2
