name: flagsmith_flutter_core
description: >-
  Core Package of Flutter Client SDK for https://www.flagsmith.com/, Flagsmith is 100% Open
  Source. Host yourself or let us take care of the hosting.

version: 4.0.0
homepage: https://github.com/Flagsmith/flagsmith-flutter-core
repository: https://github.com/Flagsmith/flagsmith-flutter-core
issue_tracker: https://github.com/Flagsmith/flagsmith-flutter-core/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.1
  encrypt: ^5.0.1
  rxdart: ^0.28.0
  json_annotation: ^4.0.1
  collection: ^1.15.0
dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.8
  http_mock_adapter: ^0.6.1
  mockito: ^5.0.15
  json_serializable: ^6.8.0
  build_runner: ^2.1.2
