name: Analyze and Test
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Dart Analyze

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter analyze
  score:
    runs-on: ubuntu-latest
    name: Dart package score

    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  publishing:
    runs-on: ubuntu-latest
    name: Dart Publish Package Test

    needs: analyze
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'any'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter pub test
